ui_hz: 25

alerts:
  battery_warning_v: 48.0
  battery_critical_v: 46.0
  motor_warning_c: 85.0
  motor_critical_c: 95.0
  hysteresis_v: 0.5
  stale_warning_ms: 600
  stale_critical_ms: 1200

ranges:
  speed_kmh: [0, 70]
  rpm: [0, 4000]
  motor_temp_c: [20, 110]
